/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package SprinklerServer.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ProgramMode implements org.apache.thrift.TEnum {
  DAY_OF_WEEK(1),
  EVEN_DAYS(2),
  ODD_DAYS(3),
  DAY_INTERVAL(4);

  private final int value;

  private ProgramMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ProgramMode findByValue(int value) { 
    switch (value) {
      case 1:
        return DAY_OF_WEEK;
      case 2:
        return EVEN_DAYS;
      case 3:
        return ODD_DAYS;
      case 4:
        return DAY_INTERVAL;
      default:
        return null;
    }
  }
}
