/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package SprinklerServer.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RunState implements org.apache.thrift.TEnum {
  RS_AUTO(1),
  RS_MANUAL(2),
  RS_RAIN(3),
  RS_OFF(4);

  private final int value;

  private RunState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RunState findByValue(int value) { 
    switch (value) {
      case 1:
        return RS_AUTO;
      case 2:
        return RS_MANUAL;
      case 3:
        return RS_RAIN;
      case 4:
        return RS_OFF;
      default:
        return null;
    }
  }
}
