/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SprinklerServer_constants.h"

namespace SprinklerServerThrift {

const SprinklerServerConstants g_SprinklerServer_constants;

SprinklerServerConstants::SprinklerServerConstants() {
}

} // namespace

