/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SprinklerServer_CONSTANTS_H
#define SprinklerServer_CONSTANTS_H

#include "SprinklerServer_types.h"

namespace SprinklerServerThrift {

class SprinklerServerConstants {
 public:
  SprinklerServerConstants();

};

extern const SprinklerServerConstants g_SprinklerServer_constants;

} // namespace

#endif
